---
title: "Abelhas e vespas como indicadores ambientais"
author: "Marília Melo Favalesso"
output: html_document
---

# Introdução

As  principais  vantagens  do  emprego  de abelhas e vespas como bioindicadoras ambiental está na ampla riqueza e abundância de seus indivíduos, no ciclo de vida curto, na fácil amostragem desses grupos, em sua fidelidade ecológica, no fornecimento de  serviços  ecológicos  essenciais,  na  relativa facilidade na identificação de gêneros e espécies, e com uma mudança na composição de suas espécies concomitante às mudanças mais pronunciadas das comunidades  vegetais,  sendo  assim  utilizadas como bioindicadores ecológicos (...). 

# Métodos

Caracterização das áreas de estudo O estudo foi realizado no estado do Paraná (Brasil), próximo às cidades de Terra Roxa e Palotina. O clima regional, segundo a classificação de Köppen (Kottek et al. 2006) adotada para o estado do Paraná, é do tipo temperado, sempre úmido (Cfa) e com verões quentes (temperatura média mensal: 21,2ºC; umidade relativa mensal: 76,17%; e precipitação anual: 1.649,7 mm). O estudo foi conduzido em uma área em restauração (FR) e em outros seis fragmentos de Floresta Estacional Semidecidual (F1-F6) (Figura 1; Tabela 1). Os cinco primeiros fragmentos utilizados como referência (...)


# Resultados

# Discussão

# Conclusão